# Generated by Django 3.0.5 on 2023-01-22 16:37

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uniqid', models.CharField(default=school.models.random_string, max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('roll', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=45, null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
            ],
        ),
    ]
